apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  kafka:
    version: 3.8.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.8"
    storage:
      type: ephemeral
      volumes:
      - id: 0
        type: ephemeral
        size: 20Gi
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
      size: 20Gi
      deleteClaim: false
  entityOperator:
    topicOperator:
      watchedNamespace: kafka-consumer-test
    userOperator: {}
  cruiseControl: {}