apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: test-topic-1
  labels:
    strimzi.io/cluster: kafka-cluster   # Name of the Kafka Cluster the topic belongs to
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824